version: '3'

services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MONGO_USER=admin
      - MONGO_PASS=admin
      - MONGO_DB=user
    command: yarn dev